import = ["/home/paff/.config/bspwm/alacritty/colors.toml", "/home/paff/.config/bspwm/alacritty/fonts.toml"]
live_config_reload = true

[colors.cursor]
cursor = "#fb4c5d"
text = "#ffffff"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
# history = 10000
# multiplier = 3
opacity = 0.91
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 23

[window.padding]
x = 10
y = 10
